# Generated by Django 4.2.2 on 2024-04-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractCV',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extract_cv', serialize=False, to='accounts.employee')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ExtractCV',
            },
        ),
    ]
