# Generated by Django 4.2.2 on 2024-05-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extractcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dzqfmaj6i/image/upload/v1712999567/hireIT/default/user_default_hx8abj.jpg', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dzqfmaj6i/image/upload/v1712999567/hireIT/default/user_default_hx8abj.jpg', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
